CREATE TABLE ADFRAME_VOTING_CATEGORY #generate
(
  ADFRAME_VOTING_CATEGORY_ID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TITLE varchar(255) NOT NULL,
  TEXT text,
  IMG varchar(200) DEFAULT 'DEFIMG_0_1.gif',
  ITEM_0 varchar(200) DEFAULT NULL,
IS_RAFFLE int(11) DEFAULT '0',
VOTES int(11) NOT NULL DEFAULT 0,
  CR_DATE datetime NOT NULL,
  END_DATE datetime DEFAULT NULL,
  IS_ACTIVE int(11) NOT NULL
);

