CREATE TABLE ADFRAME_VOTING #generate
(
  ADFRAME_VOTING_ID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ADFRAME_VOTING_CATEGORY_ID int(11) NOT NULL,
  ADFRAME_USER_ID int(11) DEFAULT NULL,
  VALUE int(11) NOT NULL,
  ITEM_0 varchar(200) NOT NULL,
  ITEM_1 varchar(200) NOT NULL,
  ITEM_2 varchar(200) NOT NULL,
  ITEM_3 varchar(200) NOT NULL,
  CR_DATE datetime NOT NULL,
  IS_ACTIVE int(11) NOT NULL
);
